### ISSUE TITLE
Counting Vignette in utHelpR can't be viewed

### ISSUE THREAD

**Issue by andreabringhurst** [ut-effectiveness/utHelpR#1]
If I'm in a project and try to pull up the Counting Vignette from utHelpR, it tells me "no vignettes found".  Here is the code I'm using in the console - vignette(package = 'utHelpR'). If I run it for utDataStoR, it provides me a list of vignettes - vignette(package = 'utDataStoR').

Joy and I are wondering if it broke when utHelpR was migrated to ut-effectiveness.

**Comment by andreabringhurst** [comment]
Joy needs to use the counting vignette in utHelpR to help establish a template for all vignettes. It currently isn't visible. I created an issue for it today in utHelpR and @cdemkegit was assigned to work on it. Because it is in a different repo, I am linking the issue here: https://github.com/ut-effectiveness/utHelpR/issues/1 .

**Comment by MattNickodemus** [comment]
@andreabr-dixie You might want to check to make sure you're loading the vignette from the package. 

```
library(devtools)
devtools::install_github("person_name/repo_name", build_vignettes = TRUE)
```

**Comment by andreabringhurst** [comment]
Matt was right, I did not have build_vignettes = TRUE when I installed the library. This is fixed and I am closing the issue.
